import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface Props {
	children: React.ReactNode;
	modal: React.ReactNode;
}
export default function RootLayout({ children, modal }: Props) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
				{modal}
			</body>
		</html>
	);
}
